#spring.application.name=CourseSellingWeb
server:
port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursesellingweb_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 210303
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    serialization:
      fail-on-empty-beans: false
    servlet:
      multipart:
        max-file-size:100MB
        max-request-size:100MB
        enabled:true

    messages:
      always-use-message-format: false
      basename: i18n/messages
      cache-seconds: -1
      encoding: UTF-8
      default-locale: en
      fallback-to-system-locale: true
    main:
      allow-bean-definition-overriding=true:
    security:
      debug: true
    allow-circular-references: true


jwt:
  expiration: 604800
  #7 days (s)
  secretKey: PstJjnP30Ohm2YKW/bgvGvk80UFeylLdzcbHcH136z4=
api:
  prefix: api/v1

  logging:
    level:
      org.springframework.security: DEBUG
      logging.level.com.project.CourseSellingWeb.filters.JwtTokenFilter: DEBUG


